function [problem, config, pop, state, controller, maxgen] = initTrial(config, problemFactory)
% initTrial - Complete trial initialization.
%
% Sets up RNG, creates problem instance via factory, validates return type,
% generates random initial population, evaluates it, and creates TrialController.
%
% Decision-space bounds are NOT cached; helpers should call problem.getDomain()
% (see ADR-0004 — single source of truth for bounds).
%
% Input:
%   config         - framework configuration struct (generated by createConfig)
%   problemFactory - function handle @(config) -> DynamicProblem instance
%                    (REQUIRED — must be a valid function handle)
%
% Output:
%   problem    - initialized DynamicProblem instance
%   config     - configuration (unchanged from input)
%   pop        - evaluated initial population [1×N Solution array]
%   state      - runtime state (gen=0, fes=popSize)
%   controller - TrialController instance
%   maxgen     - total generation budget

    % Validate problemFactory BEFORE any output assignment
    if nargin < 2 || isempty(problemFactory) || ~isa(problemFactory, 'function_handle')
        error('initTrial:missingFactory', ...
            'problemFactory must be provided as a function handle.');
    end

    state.gen = 0;
    state.fes = 0;

    rng(config.run.seed, 'twister');

    % Create problem instance via factory function
    problem = problemFactory(config);

    % Validate return type
    if ~isa(problem, 'DynamicProblem')
        error('initTrial:invalidProblem', ...
            'problemFactory must return a DynamicProblem instance, got %s', class(problem));
    end

    % Guard: popSize must be at least 2
    if config.algo.popSize < 2
        error('initTrial:invalidPopSize', ...
            'Population size must be at least 2.');
    end

    % Generate and evaluate the initial population
    N = config.algo.popSize;
    D = problem.getDecisionDims();
    domain = problem.getDomain();   % [D×2]
    lower = domain(:,1)';           % [1×D]
    upper = domain(:,2)';           % [1×D]
    decs = rand(N, D) .* (upper - lower) + lower;  % [N×D]

    pop = Solution.fromDecs(decs);
    [pop, state] = evaluatePopulation(problem, pop, state);

    state.gen = 0;
    maxgen = config.algo.maxGenPerEnv * problem.tMax;
    controller = TrialController(problem, config);
end
