function [problem, config, pop, state, controller, maxgen] = initTrial(config, problemFactory)
% initTrial - Complete trial initialization (deepened).
%
% Sets up RNG, creates problem instance via factory, validates return type,
% populates config.domain/decisionDims, generates random initial population,
% evaluates it, and creates TrialController.
%
% Input:
%   config         - framework configuration struct (generated by createConfig)
%   problemFactory - function handle @(config) -> DynamicProblem instance
%                    (optional: if omitted, obtained from config.problemFactory)
%
% Output:
%   problem    - initialized DynamicProblem instance
%   config     - configuration with added .domain and .decisionDims
%   pop        - evaluated initial population [1×N Solution array]
%   state      - runtime state (gen=0, fes=popSize)
%   controller - TrialController instance
%   maxgen     - total generation budget

    % --- Inlined from createRunState ---
    state.gen = 0;
    state.fes = 0;

    % Resolve factory (support obtaining from config.problemFactory)
    if nargin < 2 || isempty(problemFactory)
        if isfield(config, 'problemFactory')
            problemFactory = config.problemFactory;
        else
            error('initTrial:missingFactory', ...
                'problemFactory must be provided as argument or in config.problemFactory');
        end
    end

    rng(config.run.seed, 'twister');

    % Create problem instance via factory function
    problem = problemFactory(config);

    % Validate return type
    if ~isa(problem, 'DynamicProblem')
        error('initTrial:invalidProblem', ...
            'problemFactory must return a DynamicProblem instance, got %s', class(problem));
    end

    config.domain       = problem.getDomain();       % [D×2]
    config.decisionDims = problem.getDecisionDims();

    % Guard: popSize must be at least 2
    if config.algo.popSize < 2
        error('initTrial:invalidPopSize', ...
            'Population size must be at least 2.');
    end

    % --- Inlined from generateRandomPoint + initializePopulation ---
    N = config.algo.popSize;
    D = config.decisionDims;
    lower = config.domain(:,1)';   % [1×D]
    upper = config.domain(:,2)';   % [1×D]
    decs = rand(N, D) .* (upper - lower) + lower;  % [N×D]

    % --- Use static factory instead of manual loop ---
    pop = Solution.fromDecs(decs);

    % --- Evaluate (simplified 3-arg signature) ---
    [pop, state] = evaluatePopulation(problem, pop, state);

    state.gen = 0;
    maxgen = config.algo.maxGenPerEnv * problem.tMax;
    controller = TrialController(problem, config);
end
