function problem = dcdtlz2ShortFactory(config)
% dcdtlz2ShortFactory - DC-DTLZ2 problem factory with reduced horizon.
%
% Creates a DCDTLZ2Short instance (tMax=4, 4 environment changes).
% This avoids the floating-point boundary case at t=5 where the constraint
% boundary coincides exactly with the Pareto front, making it suitable for
% quick demonstrations that reliably produce HV values.
%
% Input:
%   config - framework configuration struct (generated by createConfig)
%
% Output:
%   problem - initialized DCDTLZ2Short instance

    problem = DCDTLZ2Short();
    problem.initialize(config);
end
