function problem = dcdtlz2Factory(config)
% dcdtlz2Factory - DC-DTLZ2 problem factory function.
%
% Signature: @(config) -> DynamicProblem
%
% Create and initialize a DC-DTLZ2 dynamically constrained multi-objective test problem instance.
% Can be used directly as the problemFactory argument for runBenchmark.
%
% Usage:
%   factory = @dcdtlz2Factory;
%   runBenchmark(factory, 'algo.popSize', 100);
%
% Input:
%   config - framework configuration struct (generated by createConfig)
%
% Output:
%   problem - initialized DCDTLZ2 instance (DynamicProblem subclass)

    problem = DCDTLZ2();
    problem.initialize(config);
end
