function problem = dcdtlzFactory(config)
% dcdtlzFactory - DC-DTLZ1 problem factory function.
%
% Signature: @(config) -> DynamicProblem
%
% Create and initialize a DC-DTLZ1 dynamically constrained multi-objective test problem instance.
% Can be used directly as the problemFactory argument for runBenchmark.
%
% Usage:
%   factory = @dcdtlzFactory;
%   runBenchmark(factory, 'algo.popSize', 100);
%
% Input:
%   config - framework configuration struct (generated by createConfig)
%
% Output:
%   problem - initialized DCDTLZ1 instance (DynamicProblem subclass)

    problem = DCDTLZ1();
    problem.initialize(config);
end
